const origin=COMPETITION_DATA.find(h=>h.id===document.body.dataset.hall);
const isDirectory=document.body.dataset.view==='directory';
const ce=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields={sms:'Text alerts',presale:'Advance ordering',loyalty:'Loyalty / rewards',hotball:'Hot ball'};
const params=new URLSearchParams(location.search);
let radius=[10,25,50,100].includes(Number(params.get('radius')))?Number(params.get('radius')):50;
let day=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].includes(params.get('day'))?params.get('day'):'';
let query='',map,markers=new Map(),markerLayer,rangeRing;
const byId=id=>document.getElementById(id);
function scheduleHTML(h){const entries=Object.entries(h.schedule||{});return entries.length?entries.map(([d,s])=>`<div class="schedule-line"><strong>${ce(d)}</strong> ${ce(s.frequency||'')} ${s.doors?'· Doors '+ce(s.doors):''}${s.session?' · '+ce(s.session):''}${s.program?`<p class="small muted">${ce(s.program)}</p>`:''}</div>`).join(''):'<p class="muted">Session details were not available in the reviewed material.</p>';}
function sourceNote(h){return h.reviewed?'Website reviewed September 10, 2026':'Bingo Scout listing · current program not rechecked';}
function featuresHTML(h){return Object.entries(fields).map(([k,label])=>`<span class="badge ${h.features[k]==='yes'?'yes':''}" title="${ce(compLabel(h.features[k]))}">${ce(label)}: ${h.features[k]==='yes'?'visible':h.features[k]==='listed'?'Scout listing':h.features[k]==='not-visible'?'not found':'unknown'}</span>`).join('');}
function distanceText(h){return h.id===origin.id?'Your hall':h.distance<.15?'Same venue / immediate area':h.distance.toFixed(1)+' miles away';}
function venueType(h){return h.category?`<span class="badge">${ce(h.category)}</span>`:'';}
function fullCard(h){return `<article class="directory-card" id="hall-${ce(h.id)}"><header><div><span class="eyebrow">${ce(distanceText(h))}</span><h3>${ce(h.name)}</h3><p class="muted">${ce(h.address)}</p>${venueType(h)}</div><a class="button" href="${ce(h.url)}" target="_blank" rel="noopener noreferrer">Hall website ↗</a></header><div class="detail-grid"><div><h3>Published schedule</h3>${scheduleHTML(h)}</div><div><h3>What players can find</h3><p>${featuresHTML(h)}</p><p><strong>Buy-in:</strong> ${ce(h.buyIn||'Not published in the reviewed material.')}</p><p>${ce(h.notes)}</p></div></div>${h.promotions?.length?`<details><summary>Listed offers</summary>${h.promotions.map(p=>`<p><b>${ce(p.title)}</b> ${ce(p.text)}</p>`).join('')}</details>`:''}<details class="evidence"><summary>Sources & review notes</summary><p class="small muted">${ce(sourceNote(h))}. “Not found” describes the pages reviewed, not the hall’s internal systems. An ordering or reservation link does not by itself establish paid presales.</p>${h.evidence.map(e=>`<p><b>${ce(e.topic||e.feature||'Source')}</b> ${ce(e.observed)} <a href="${ce(e.url||h.url)}" target="_blank" rel="noopener noreferrer">Source ↗</a></p>`).join('')}<p class="small"><a href="${ce(h.url)}" target="_blank" rel="noopener noreferrer">Published hall page ↗</a>${/^https:/.test(h.coordinateSource)?` · <a href="${ce(h.coordinateSource)}" target="_blank" rel="noopener noreferrer">Address map source ↗</a>`:''}</p></details></article>`;}
function viewLinks(){for(const el of document.querySelectorAll('[data-view-link]'))el.href=el.dataset.viewLink+'.html?'+new URLSearchParams({radius,day});}
function controlsHTML(){return `<div class="controls"><fieldset id="radius" class="choice-field"><legend>Distance from your hall</legend><div class="radius-grid">${[10,25,50,100].map(n=>`<label class="choice"><input type="radio" name="radius-choice" value="${n}" ${n===radius?'checked':''}><span>${n} <small>mi</small></span></label>`).join('')}</div></fieldset><fieldset id="day" class="choice-field"><legend>Game day</legend><div class="day-grid">${['','Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<label class="choice"><input type="radio" name="day-choice" value="${d}" ${d===day?'checked':''}><span>${d||'All days'}</span></label>`).join('')}</div></fieldset><label class="search-label"><span class="sr-only">Find a competitor</span><input id="search" type="search" placeholder="Search a hall or city…"></label></div>`;}
function chooseHall(id){const h=COMPETITION_DATA.find(h=>h.id===id);if(!h)return;const item={...h,distance:compMiles(origin,h)};byId('map-detail').innerHTML=`<button class="close" id="close-detail" aria-label="Close hall details">×</button><span class="eyebrow">${ce(distanceText(item))}</span><h2>${ce(h.name)}</h2><p class="muted">${ce(h.address)}</p>${featuresHTML(h)}<p>${ce(h.buyIn||'Buy-in not listed in this review.')}</p><p class="small">${ce(h.days.join(' · ')||'Days not confirmed')}</p><p><a href="competitors.html?${new URLSearchParams({radius,day})}#hall-${ce(h.id)}">Full hall details & sources →</a></p><p class="small muted">${ce(sourceNote(h))}</p>`;byId('map-detail').hidden=false;byId('close-detail').onclick=()=>byId('map-detail').hidden=true;if(map){map.panTo([h.lat,h.lng]);markers.get(id)?.openPopup();}for(const el of document.querySelectorAll('[data-hall-card]'))el.classList.toggle('active',el.dataset.hallCard===id);}
function renderResults(){
 const nearby=compNearby(COMPETITION_DATA,origin,radius,day).filter(h=>(h.name+' '+h.address).toLowerCase().includes(query.toLowerCase()));
 byId('results-label').textContent=`${nearby.length} nearby bingo programs`;
 if(byId('map-summary'))byId('map-summary').innerHTML=`<div><strong>${nearby.length}</strong><span>Nearby programs</span></div><div><strong>${nearby.filter(h=>h.sameDays.length).length}</strong><span>Shared game days</span></div><div><strong>${radius}<small> mi</small></strong><span>Search radius</span></div>`;
 viewLinks();
 if(isDirectory){
  byId('stats').innerHTML=`<div class="stat"><strong>${nearby.length}</strong>Programs in this view</div><div class="stat"><strong>${nearby.filter(h=>h.sameDays.length).length}</strong>List at least one of your game days</div><div class="stat"><strong>${nearby.filter(h=>h.reviewed).length}</strong>Websites checked for this review</div>`;
  byId('opportunities').innerHTML=compOpportunities(origin,nearby).map((o,i)=>`<article class="opportunity"><span class="number">0${i+1}</span><h3>${ce(o.title)}</h3><p>${ce(o.text)}</p>${o.example?`<p class="small muted">${ce(o.example)}</p>`:''}</article>`).join('');
  byId('comparison').innerHTML=`<table><thead><tr><th>Hall / program</th><th>Distance</th><th>Listed days</th>${Object.values(fields).map(x=>`<th>${ce(x)}</th>`).join('')}</tr></thead><tbody>${[origin,...nearby].map(h=>`<tr ${h.id===origin.id?'class="your-row"':''}><td><a href="#hall-${ce(h.id)}">${ce(h.name)}</a>${h.id===origin.id?'<p>Your hall</p>':''}<p class="small muted">${ce(sourceNote(h))}</p></td><td>${ce(distanceText(h))}</td><td>${ce(h.days.join(', ')||'Not confirmed')}</td>${Object.keys(fields).map(k=>`<td>${ce(compLabel(h.features[k]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  byId('hall-results').innerHTML=fullCard(origin)+nearby.map(fullCard).join('')+(nearby.length?'':'<p class="empty">No competitors match these filters. Try a wider distance or another day.</p>');
 }else{
  byId('hall-results').innerHTML=nearby.map((h,i)=>`<article class="hall-card ${h.sameDays.length?'shared-card':''}" data-hall-card="${ce(h.id)}"><div class="card-topline"><span class="hall-number">${i+1}</span><span class="distance">${h.distance<.15?'Same venue / area':h.distance.toFixed(1)+' mi'}</span>${h.sameDays.length?'<span class="shared-label">Shared day</span>':''}</div><h3><button data-open-hall="${ce(h.id)}">${ce(h.name)}</button></h3><div class="card-days">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<span class="${h.days.includes(d)?'on':''}" title="${h.days.includes(d)?'Listed '+d:'No '+d+' listed'}">${d.slice(0,2)}</span>`).join('')}</div><p class="${/\$/.test(h.buyIn)?'card-price':'small muted'}">${ce(h.buyIn||h.address)}</p><div class="card-features">${Object.entries(fields).filter(([k])=>h.features[k]==='yes'||h.features[k]==='listed').slice(0,3).map(([k,v])=>`<span title="${ce(compLabel(h.features[k]))}">${ce(v)}</span>`).join('')}</div><p class="card-source">${h.reviewed?'Website reviewed · Sep 10':'Bingo Scout listing · not rechecked'}</p></article>`).join('')||'<p class="empty">No halls match these filters. Try a wider distance or another day.</p>';
  for(const el of document.querySelectorAll('[data-open-hall]'))el.onclick=()=>chooseHall(el.dataset.openHall);
  if(map){markerLayer.clearLayers();markers.clear();for(const [i,h] of [origin,...nearby].entries()){const own=h.id===origin.id,shared=h.sameDays?.length;const icon=L.divIcon({className:'',html:`<div class="map-pin ${own?'own':shared?'shared':''}">${own?'<span class="origin-core"></span>':i}</div>`,iconSize:own?[34,34]:[27,27],iconAnchor:own?[17,17]:[13.5,13.5]});const marker=L.marker([h.lat,h.lng],{icon,title:h.name,zIndexOffset:own?1000:0}).addTo(markerLayer).bindPopup(`<span class="popup-kicker">${own?'YOUR HALL':ce(h.distance.toFixed(1))+' MILES AWAY'}</span><h3>${ce(h.name)}</h3><p>${ce(h.address)}</p><a class="popup-link" href="competitors.html?${new URLSearchParams({radius,day})}#hall-${ce(h.id)}">Full comparison →</a>`);if(own)marker.bindTooltip('YOUR HALL',{permanent:true,direction:'top',className:'origin-label',offset:[0,-22]});marker.on('click',()=>chooseHall(h.id));markers.set(h.id,marker);}if(rangeRing)rangeRing.remove();rangeRing=L.layerGroup().addTo(map);for(const miles of [...new Set([10,25,radius])].filter(n=>n<=radius)){L.circle([origin.lat,origin.lng],{radius:miles*1609.344,color:'#62d3a4',weight:1,dashArray:miles===radius?'6 8':'2 7',fillColor:'#62d3a4',fillOpacity:.025,opacity:miles===radius?.6:.28,interactive:false}).addTo(rangeRing);}}
 }
}
function initCompetition(){
 if(!origin){byId('main').textContent='This hall could not be found.';return;}
 byId('controls').innerHTML=controlsHTML();
 byId('radius').onchange=e=>{radius=Number(e.target.value);renderResults();};byId('day').onchange=e=>{day=e.target.value;renderResults();};byId('search').oninput=e=>{query=e.target.value;renderResults();};
 if(!isDirectory&&typeof L!=='undefined'){
  map=L.map('map',{scrollWheelZoom:true}).setView([origin.lat,origin.lng],10);markerLayer=L.layerGroup().addTo(map);
  const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,className:'scout-dark-basemap',attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}).addTo(map);
  tiles.on('tileerror',()=>{byId('map-status').textContent='Street map unavailable. Hall pins and the competitor directory remain available.';});byId('map').classList.add('loaded');
  byId('recenter').onclick=()=>map.setView([origin.lat,origin.lng],10);
 }
 renderResults();
 if(isDirectory&&location.hash.startsWith('#hall-'))document.getElementById(location.hash.slice(1))?.scrollIntoView();
}
initCompetition();
